nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.2.2.cjs

npmScopes:
  fortawesome:
    npmRegistryServer: https://git.fgtclb.com/api/v4/projects/299/packages/npm/
    npmAlwaysAuth: true
    npmAuthToken: ${FRONTEND_FONTAWESOME_REPO_TOKEN}
